services:
  api1: &api
    build: .
    hostname: api1
    environment:
      - DATABASE_URL=postgresql://rinha:rinha@db:5432/rinha
      - PORTA_API=8080
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  api2:
    <<: *api
    hostname: api2

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db:
    image: postgres:16.1-alpine
    hostname: db
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "350MB"
  
  locust:
    build:
      context: .
      dockerfile: locust/Dockerfile
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/home/locust
    command: -f /home/locust/locustfile.py --host http://nginx:9999
    depends_on:
      - nginx

networks:
  default:
    driver: bridge


